language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
stages:
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: deploy backend
      script: skip
      deploy: &heroku
        provider: heroku
        app: webapps05backend
        api-key: 03b286f8-6ecb-460f-8e9d-1245a883a64c
      on:
        branch: master